"""
Migrate old data from oslm-crawler/data to output/, with the following file mappings:

- merged-models-info.jsonl -> model_data.jsonl
- merged-datasets-info.jsonl -> dataset_data.jsonl
- accumulated-models-info.jsonl -> acc_model_data.jsonl
- accumulated-daatsets-info.jsonl -> acc_dataset_data.jsonl
- model-summary.csv -> model_summary.csv
- data-summary.csv -> dataset_summary.csv
- infra-summary.csv -> infra_summary.csv
- eval-summary.csv -> eval_summary.csv
- model-accumulated-summary.csv -> acc_model_summary.csv
- data-accumulated-summary.csv -> acc_dataset_summary.csv
- model-summary-delta.csv -> delta_model_summary.csv
- data-summary-delta.csv -> delta_dataset_summary.csv
- model-rank.csv -> model_rank.csv
- data-rank.csv -> dataset_rank.csv
- infra-rank.csv -> infra_rank.csv
- eval-rank.csv -> eval_rank.csv
- overall-rank.csv -> overall_rank.csv
- model-accumulated-rank.csv -> acc_model_rank.csv
- data-accumulated-rank.csv -> acc_dataset_rank.csv
- overall-accumulated-rank.csv -> acc_overall_rank.csv
- domestic-rank.csv -> CN_overall_rank.csv
- domestic-accumulated-rank.csv -> CN_acc_overall_rank.csv

New data is generated by code in src/oslm-analyst/processors/osir_lmts.py.

If fields are missing in old data, set them to null in new data.

Old data structure reference: oslm-crawler/data/2026-02-09

New data structure reference: output/osir-lmts_2026-03
"""

import json
import jsonlines
import pandas as pd
from pathlib import Path
from datetime import datetime
from loguru import logger


def convert_old_date_to_month(old_date: str) -> str:
    """Convert old date format (YYYY-MM-DD) to month format (YYYY-MM)"""
    try:
        dt = datetime.strptime(old_date, '%Y-%m-%d')
        return dt.strftime('%Y-%m')
    except ValueError:
        # If already in YYYY-MM format, return as is
        return old_date


def migrate_model_jsonl(old_path: Path, new_path: Path, is_accumulated: bool = False):
    """Migrate model JSONL file"""
    records = []
    with jsonlines.open(old_path) as reader:
        for line in reader:
            # Build identifier
            repo = line.get('repo', line.get('org', ''))
            model_name = line.get('model_name', '')
            if repo and model_name:
                identifier = f'{repo}/{model_name}'
            else:
                identifier = model_name or repo

            date_crawl = line.get('date_crawl', '')
            if not is_accumulated:
                date_crawl = convert_old_date_to_month(date_crawl)

            if is_accumulated:
                # Accumulated data format
                record = {
                    'identifier': identifier,
                    'date_crawl': date_crawl,
                    'likes': line.get('likes') if line.get('likes') is not None else None,
                    'discussions': line.get('community') if line.get('community') is not None else None,
                    'descendants': line.get('descendants') if line.get('descendants') is not None else None,
                    'modality': line.get('modality'),
                    'downloads': line.get('accumulated_downloads') if line.get('accumulated_downloads') is not None else None,
                }
            else:
                # Regular data format
                record = {
                    'identifier': identifier,
                    'date_crawl': date_crawl,
                    'downloads_last_month': line.get('downloads_last_month') if line.get('downloads_last_month') is not None else None,
                    'likes': line.get('likes') if line.get('likes') is not None else None,
                    'discussions': line.get('community') if line.get('community') is not None else None,
                    'descendants': line.get('descendants') if line.get('descendants') is not None else None,
                    'modality': line.get('modality'),
                }
            records.append(record)

    new_path.parent.mkdir(parents=True, exist_ok=True)
    with jsonlines.open(new_path, mode='w') as writer:
        for record in records:
            writer.write(record)

    logger.info(f'Migrated {len(records)} records from {old_path.name} to {new_path.name}')


def migrate_dataset_jsonl(old_path: Path, new_path: Path, is_accumulated: bool = False):
    """Migrate dataset JSONL file"""
    records = []
    with jsonlines.open(old_path) as reader:
        for line in reader:
            # Build identifier
            repo = line.get('repo', line.get('org', ''))
            dataset_name = line.get('dataset_name', '')
            if repo and dataset_name:
                identifier = f'{repo}/{dataset_name}'
            else:
                identifier = dataset_name or repo

            date_crawl = line.get('date_crawl', '')
            if not is_accumulated:
                date_crawl = convert_old_date_to_month(date_crawl)

            if is_accumulated:
                # Accumulated data format
                record = {
                    'identifier': identifier,
                    'date_crawl': date_crawl,
                    'likes': line.get('likes') if line.get('likes') is not None else None,
                    'discussions': line.get('community') if line.get('community') is not None else None,
                    'descendants': line.get('descendants') if line.get('descendants') is not None else None,
                    'modality': line.get('modality'),
                    'lifecycle': line.get('lifecycle'),
                    'downloads': line.get('accumulated_downloads') if line.get('accumulated_downloads') is not None else None,
                }
            else:
                # Regular data format
                record = {
                    'identifier': identifier,
                    'date_crawl': date_crawl,
                    'downloads_last_month': line.get('downloads_last_month') if line.get('downloads_last_month') is not None else None,
                    'likes': line.get('likes') if line.get('likes') is not None else None,
                    'discussions': line.get('community') if line.get('community') is not None else None,
                    'descendants': line.get('descendants') if line.get('descendants') is not None else None,
                    'modality': line.get('modality'),
                    'lifecycle': line.get('lifecycle'),
                }
            records.append(record)

    new_path.parent.mkdir(parents=True, exist_ok=True)
    with jsonlines.open(new_path, mode='w') as writer:
        for record in records:
            writer.write(record)

    logger.info(f'Migrated {len(records)} records from {old_path.name} to {new_path.name}')


def rename_columns(df: pd.DataFrame, column_mapping: dict) -> pd.DataFrame:
    """Rename DataFrame columns"""
    df = df.copy()
    for old_col, new_col in column_mapping.items():
        if old_col in df.columns and new_col not in df.columns:
            df = df.rename(columns={old_col: new_col})
    return df


def migrate_summary_csv(old_path: Path, new_path: Path):
    """Migrate summary CSV file"""
    df = pd.read_csv(old_path)

    # Rename column: delta rank -> delta_rank
    if 'delta rank' in df.columns:
        df = df.rename(columns={'delta rank': 'delta_rank'})

    # For overall-rank.csv and domestic-rank.csv, rename dimension columns
    if 'data' in df.columns and 'model' in df.columns:
        df = df.rename(columns={
            'data': 'dataset_influence',
            'model': 'model_influence',
            'infra': 'infra_influence',
            'eval': 'eval_influence',
        })

    new_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(new_path, index=False)
    logger.info(f'Migrated CSV from {old_path.name} to {new_path.name}')


def get_month_from_old_dir(old_dir: Path) -> str:
    """Get month from old data directory name"""
    dir_name = old_dir.name
    try:
        dt = datetime.strptime(dir_name, '%Y-%m-%d')
        return dt.strftime('%Y-%m')
    except ValueError:
        return dir_name


def migrate_single_directory(old_dir: Path, output_root: Path):
    """Migrate a single old data directory"""
    month = get_month_from_old_dir(old_dir)
    new_dir = output_root / f'osir-lmts_{month}'

    logger.info(f'Migrating {old_dir} to {new_dir}')

    # File mappings
    file_mappings = [
        # (old filename, new filename, migrate function, extra kwargs)
        ('merged-models-info.jsonl', 'model_data.jsonl', migrate_model_jsonl, {'is_accumulated': False}),
        ('merged-datasets-info.jsonl', 'dataset_data.jsonl', migrate_dataset_jsonl, {'is_accumulated': False}),
        ('accumulated-models-info.jsonl', 'acc_model_data.jsonl', migrate_model_jsonl, {'is_accumulated': True}),
        ('accumulated-datasets-info.jsonl', 'acc_dataset_data.jsonl', migrate_dataset_jsonl, {'is_accumulated': True}),
        ('accumulated-daatsets-info.jsonl', 'acc_dataset_data.jsonl', migrate_dataset_jsonl, {'is_accumulated': True}),
    ]

    # Migrate JSONL files
    for old_name, new_name, migrate_func, kwargs in file_mappings:
        old_path = old_dir / old_name
        new_path = new_dir / new_name
        if old_path.exists():
            migrate_func(old_path, new_path, **kwargs)
        elif old_name != 'accumulated-daatsets-info.jsonl':
            # Only warn if not the misspelled filename (since we have two possible filenames)
            logger.warning(f'Skipping {old_name}, file not found')

    # CSV file mappings (direct copy with column renaming)
    csv_mappings = [
        ('model-summary.csv', 'model_summary.csv'),
        ('data-summary.csv', 'dataset_summary.csv'),
        ('infra-summary.csv', 'infra_summary.csv'),
        ('eval-summary.csv', 'eval_summary.csv'),
        ('model-accumulated-summary.csv', 'acc_model_summary.csv'),
        ('data-accumulated-summary.csv', 'acc_dataset_summary.csv'),
        ('model-summary-delta.csv', 'delta_model_summary.csv'),
        ('data-summary-delta.csv', 'delta_dataset_summary.csv'),
        ('model-rank.csv', 'model_rank.csv'),
        ('data-rank.csv', 'dataset_rank.csv'),
        ('infra-rank.csv', 'infra_rank.csv'),
        ('eval-rank.csv', 'eval_rank.csv'),
        ('overall-rank.csv', 'overall_rank.csv'),
        ('model-accumulated-rank.csv', 'acc_model_rank.csv'),
        ('data-accumulated-rank.csv', 'acc_dataset_rank.csv'),
        ('overall-accumulated-rank.csv', 'acc_overall_rank.csv'),
        ('domestic-rank.csv', 'CN_overall_rank.csv'),
        ('domestic-accumulated-rank.csv', 'CN_acc_overall_rank.csv'),
    ]

    for old_name, new_name in csv_mappings:
        old_path = old_dir / old_name
        new_path = new_dir / new_name
        if old_path.exists():
            migrate_summary_csv(old_path, new_path)
        else:
            logger.warning(f'Skipping {old_name}, file not found')

    logger.info(f'Completed migration for {old_dir}')


def main():
    project_root = Path(__file__).parents[2]
    old_data_root = project_root / 'oslm-crawler' / 'data'
    output_root = project_root / 'output'

    logger.info(f'Starting OSIR-LMTS data migration')
    logger.info(f'Old data root: {old_data_root}')
    logger.info(f'Output root: {output_root}')

    # Get all old data directories
    old_dirs = []
    for child in old_data_root.iterdir():
        if child.is_dir() and not child.name.startswith('.') and child.name != 'temp':
            old_dirs.append(child)

    old_dirs = sorted(old_dirs)
    logger.info(f'Found {len(old_dirs)} old data directories')

    # Migrate each directory
    for old_dir in old_dirs:
        try:
            migrate_single_directory(old_dir, output_root)
        except Exception as e:
            logger.error(f'Failed to migrate {old_dir}: {e}')

    logger.info('Migration complete!')


if __name__ == '__main__':
    main()